export const PROVIDER_TAGS = [
  "Alimentos",
  "Restaurante",
  "Comida a domicilio",
  "Pizza",
  "Hamburguesas",
  "Tacos",
  "Birria",
  "Comida mexicana",
  "Comida casera",
  "Catering",
  "Eventos",
  "Chef privado",
  "Chef para eventos",
  "Canapés",
  "Taquizas",
  "Sushi",
  "Botanas",
  "Snacks",
  "Repostería",
  "Pasteles",
  "Pasteles personalizados",
  "Postres",
  "Sin azúcar",
  "Sin gluten",
  "Productos orgánicos",
  "Miel orgánica",
  "Frutas deshidratadas",
  "Condimentos",
  "Ingredientes",
  "Mercado",
  "Tienda de alimentos",
  "Bebidas alcohólicas",
  "Destilados",
  "Raicilla",
  "Autos",
  "Mecánico",
  "Aire acondicionado automotriz",
  "Polarizado",
  "Renta de autos",
  "Compra de autos",
  "Transporte",
  "Transporte aeropuerto",
  "Taxi",
  "Fletes",
  "Mudanzas",
  "Llantera",
  "Llantera móvil",
  "Grúa",
  "Emergencias viales",
  "Belleza",
  "Uñas",
  "Estética",
  "Estética infantil",
  "Maquillaje",
  "Faciales",
  "Cuidado de la piel",
  "Depilación",
  "Permanente",
  "Tatuajes",
  "Tatuajes de henna",
  "Bienes raíces",
  "Compra de propiedades",
  "Venta de propiedades",
  "Rentas",
  "Hospedaje",
  "Hospedaje para grupos",
  "Bungalows",
  "Penthouse",
  "Bienestar",
  "Terapias",
  "Psicología",
  "Terapias holísticas",
  "Aromaterapia",
  "Access Bars",
  "Masajes",
  "Masajes a domicilio",
  "Reflexología",
  "Consultoría de lactancia",
  "Doula",
  "Deportes",
  "Clases deportivas",
  "Gimnasio",
  "Entrenador personal",
  "Fisioterapia",
  "Yoga",
  "Natación",
  "Natación a domicilio",
  "Fútbol",
  "Box",
  "Taekwondo",
  "Voleibol",
  "Danza",
  "Ballet",
  "Spinning",
  "Surf",
  "Trekking",
  "Casa y decoración",
  "Muebles",
  "Decoración",
  "Accesorios",
  "Velas",
  "Murales",
  "Persianas",
  "Cortinas",
  "Cocinas",
  "Ventanas",
  "Chapas eléctricas",
  "Aires acondicionados",
  "Blancos",
  "Paneles solares",
  "Energía renovable",
  "Emergencias",
  "Rescate animal",
  "Protección civil",
  "Bomberos",
  "Policía",
  "Vialidad",
  "Centro de justicia",
  "Entretenimiento",
  "Parques",
  "Juegos infantiles",
  "Campamentos",
  "Tours",
  "Avistamiento de ballenas",
  "Pesca",
  "Snorkel",
  "Buceo",
  "Ludoteca",
  "Educación",
  "Escuela",
  "Preescolar",
  "Primaria",
  "Secundaria",
  "Actividades extracurriculares",
  "Arte para niños",
  "Música",
  "Clases de piano",
  "Canto",
  "Fotografía",
  "Dibujo y pintura",
  "Ajedrez",
  "Regularización escolar",
  "Clases de inglés",
  "Clases de español",
  "Cocina",
  "Cooking class",
  "Fiestas",
  "Piñatas",
  "Bolos",
  "Decoración de fiestas",
  "Renta de mobiliario",
  "Brincolines",
  "Letras gigantes",
  "Shows",
  "Magos",
  "Pintacaritas",
  "Renta de cristalería",
  "Renta de mantelería",
  "Flores",
  "Fotografía de eventos",
  "Bodas",
  "Publicidad",
  "Diseño gráfico",
  "Impresiones",
  "Viniles",
  "Lonas",
  "Sublimado",
  "Sellos",
  "Fotografía comercial",
  "Fotos para pasaporte",
  "Mascotas",
  "Entrenamiento canino",
  "Cuidado de mascotas",
  "Veterinario",
  "Veterinario a domicilio",
  "Urgencias veterinarias",
  "Albergue de mascotas",
  "Cremación de mascotas",
  "Salud",
  "Médico",
  "Pediatra",
  "Ginecólogo",
  "Dermatólogo",
  "Dermatólogo pediatra",
  "Oftalmólogo",
  "Oftalmólogo pediatra",
  "Alergólogo",
  "Urólogo",
  "Ortopedia",
  "Otorrinolaringólogo",
  "Neumólogo",
  "Neurólogo",
  "Quiropráctico",
  "Dentista",
  "Odontopediatra",
  "Nutriólogo",
  "Endocrinólogo",
  "Medicina natural",
  "Enfermería",
  "Medio ambiente",
  "Reciclaje",
  "Basura electrónica",
  "Trámites ambientales",
  "Conservación",
  "Denuncias ambientales",
  "Oficios",
  "Electricista",
  "Plomero",
  "Carpintero",
  "Pintor",
  "Impermeabilización",
  "Instalaciones",
  "Todólogo",
  "Aluminero",
  "Limpieza de casa",
  "Limpieza profunda",
  "Limpieza de obra",
  "Lavandería",
  "Costurera",
  "Arreglos de ropa",
  "Reparación electrónica",
  "Reparación de computadoras",
  "Reparación de celulares",
  "Afilado de cuchillos",
  "Tapicería",
  "Jardinería",
  "Limpieza de albercas",
  "Fumigación",
  "Cocineras",
  "Servicios legales",
  "Notaría",
  "Abogados",
  "Trámites legales",
  "Servicios básicos",
  "Internet",
  "Telefonía",
  "Gas",
  "Agua",
  "Electricidad",
  "Servicios administrativos",
  "Migración",
  "Asesor de seguros",
  "Contador",
  "Afore",
  "Asesor financiero",
  "Renta",
  "Renta de equipo",
  "Renta de sonido",
  "Mandaditos",
] as const;

